title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Sobre mim
   url: /about
 - title: Contato
   url: /contact

social:
   github: joaoplsaraiva
   twitter: joaoplsaraiva
   facebook: joaoplsaraiva
   email: joaoplsaraiva@gmail.com

google_analytics: "UA-58263416-1"
